// SPDX-License-Identifier: MIT
//! AST → C source emitter.
//!
//! Each expression renders as a C snippet that produces a value of
//! one of the runtime types (`int64_t`, `double`, `bool`,
//! `phc_string`). Statements render as straight C statements.
//! Anything not yet supported emits a `phc_panic("codegen TODO")`
//! call so the produced binary fails loud at the matching site.
//!
//! Codegen tracks the interpreter's I1..I7 ladder. Today: I1
//! (literals + Logger::info + interpolation) plus I2 (arithmetic +
//! locals + control flow + user function calls with args + non-void
//! returns).

use phc_ast::{
    BinOp, ClassDecl, ClassMember, ConstructDecl, EnumDecl, Expr, FunctionDecl, Item, MatchArm,
    Pattern, SourceFile, Stmt, StrPart, TraitDecl, UnaryOp,
};
use phc_errors::{Diagnostic, Severity};
use phc_semantic::{Resolved, SymbolKind};
use phc_span::Span;
use phc_typecheck::{Primitive, Ty, Typed};

use crate::CodegenOutput;

/// Emit a complete C translation unit for `file`.
pub fn emit_c(file: &SourceFile, resolved: &Resolved, typed: &Typed) -> CodegenOutput {
    let mut out = CodegenOutput::default();
    let mut emitter = Emitter {
        buf: String::new(),
        diagnostics: &mut out.diagnostics,
        resolved,
        typed,
        file,
    };
    emitter.emit_prelude();
    // Phase 0: enum typedefs first — class fields and method
    // signatures may reference them.
    for item in &file.items {
        if let Item::Enum(e) = item {
            emitter.emit_enum(e);
        }
    }
    // Phase 1: forward struct decls so methods can reference each
    // other's instance pointer types in any order.
    for item in &file.items {
        if let Item::Class(c) = item {
            emitter.emit_class_struct_fwd(c);
        }
    }
    emitter.buf.push('\n');
    // Phase 2: full struct definitions with fields.
    for item in &file.items {
        if let Item::Class(c) = item {
            emitter.emit_class_struct(c);
        }
    }
    // Phase 3: forward-decl every free function and method so call
    // order does not depend on declaration order.
    for item in &file.items {
        match item {
            Item::Function(f) => emitter.emit_function_decl(f),
            Item::Class(c) => emitter.emit_class_member_decls(c),
            _ => {}
        }
    }
    emitter.buf.push('\n');
    // Phase 4: bodies.
    for item in &file.items {
        match item {
            Item::Function(f) => emitter.emit_function(f),
            Item::Class(c) => emitter.emit_class_bodies(c),
            _ => {}
        }
    }
    emitter.emit_main_wrapper(file);
    out.c_source = emitter.buf;
    out
}

struct Emitter<'a> {
    buf: String,
    diagnostics: &'a mut Vec<Diagnostic>,
    resolved: &'a Resolved,
    typed: &'a Typed,
    file: &'a SourceFile,
}

impl<'a> Emitter<'a> {
    fn emit_prelude(&mut self) {
        self.buf
            .push_str("/* Generated by phc-codegen — do not edit. */\n");
        self.buf.push_str("#include \"phc_runtime.h\"\n\n");
    }

    /// Map a phc TypeRef to the C type the emitter will use. Single-
    /// segment paths recognise stdlib primitives and class names from
    /// the resolver; everything else falls back to `phc_value`.
    fn c_type_for(&self, t: &phc_ast::TypeRef) -> String {
        if t.path.len() != 1 {
            return "phc_value".into();
        }
        let name = t.path[0].name.as_str();
        match name {
            "int" => "int64_t".into(),
            "float" => "double".into(),
            "bool" => "bool".into(),
            "string" => "phc_string".into(),
            "void" => "void".into(),
            _ => {
                if self.is_class(name) {
                    format!("phc_obj_{name}*")
                } else if self.is_enum(name) {
                    format!("phc_enum_{name}")
                } else {
                    "phc_value".into()
                }
            }
        }
    }

    /// Like c_type_for but consumes a typecheck-level Ty so match
    /// inference can dispatch on the recovered scrutinee / result
    /// type. Disambiguates Path between class (pointer) and enum
    /// (value) using the resolver's symbol kinds.
    fn ty_to_c(&self, ty: &Ty) -> String {
        match ty {
            Ty::Primitive(p) => match p {
                Primitive::Int => "int64_t".into(),
                Primitive::Float => "double".into(),
                Primitive::Bool => "bool".into(),
                Primitive::String => "phc_string".into(),
                Primitive::Void => "void".into(),
                Primitive::Byte => "uint8_t".into(),
                Primitive::Bytes => "phc_string".into(),
            },
            Ty::Path { path, .. } if path.len() == 1 => {
                let name = path[0].as_str();
                if self.is_class(name) {
                    format!("phc_obj_{name}*")
                } else if self.is_enum(name) {
                    format!("phc_enum_{name}")
                } else {
                    "int64_t".into()
                }
            }
            _ => "int64_t".into(),
        }
    }

    fn is_enum(&self, name: &str) -> bool {
        self.resolved
            .top_level
            .get(name)
            .map(|id| self.resolved.symbol(*id).kind == SymbolKind::Enum)
            .unwrap_or(false)
    }

    fn is_class(&self, name: &str) -> bool {
        self.resolved
            .top_level
            .get(name)
            .map(|id| self.resolved.symbol(*id).kind == SymbolKind::Class)
            .unwrap_or(false)
    }

    fn function_signature(&self, f: &FunctionDecl) -> String {
        let return_c = self.c_type_for(&f.return_type);
        let params: Vec<String> = f
            .params
            .iter()
            .map(|p| {
                format!(
                    "{} phc_var_{}",
                    self.c_type_for(&p.ty),
                    mangle(&p.name.name)
                )
            })
            .collect();
        let param_list = if params.is_empty() {
            "void".to_string()
        } else {
            params.join(", ")
        };
        format!("static {} phc_{}({})", return_c, f.name.name, param_list)
    }

    /// Method signature: `static <ret> phc_method_<Class>_<name>(
    /// phc_obj_<Class>* phc_var_this, ...)`.
    fn method_signature(&self, class: &str, m: &FunctionDecl) -> String {
        let return_c = self.c_type_for(&m.return_type);
        let mut params = vec![format!("phc_obj_{class}* phc_var_this")];
        for p in &m.params {
            params.push(format!(
                "{} phc_var_{}",
                self.c_type_for(&p.ty),
                mangle(&p.name.name)
            ));
        }
        format!(
            "static {} phc_method_{class}_{}({})",
            return_c,
            m.name.name,
            params.join(", ")
        )
    }

    /// Constructor signature: `static phc_obj_<Class>* phc_construct_<Class>(args...)`.
    fn construct_signature(&self, class: &str, c: &ConstructDecl) -> String {
        let mut params: Vec<String> = c
            .params
            .iter()
            .map(|p| {
                format!(
                    "{} phc_var_{}",
                    self.c_type_for(&p.ty),
                    mangle(&p.name.name)
                )
            })
            .collect();
        if params.is_empty() {
            params.push("void".into());
        }
        format!(
            "static phc_obj_{class}* phc_construct_{class}({})",
            params.join(", ")
        )
    }

    // ===== Enums =====

    fn emit_enum(&mut self, e: &EnumDecl) {
        let name = &e.name.name;
        self.buf.push_str("typedef enum {\n");
        for v in &e.variants {
            self.buf
                .push_str(&format!("    phc_enum_{name}_{},\n", v.name.name));
        }
        self.buf.push_str(&format!("}} phc_enum_{name};\n\n"));
    }

    // ===== Classes =====

    fn emit_class_struct_fwd(&mut self, c: &ClassDecl) {
        let name = &c.name.name;
        self.buf
            .push_str(&format!("typedef struct phc_obj_{name} phc_obj_{name};\n"));
    }

    fn emit_class_struct(&mut self, c: &ClassDecl) {
        let name = &c.name.name;
        self.buf.push_str(&format!("struct phc_obj_{name} {{\n"));
        // Promoted constructor params first, then explicit fields.
        if let Some(con) = find_constructor(c) {
            for p in &con.params {
                if p.promoted {
                    self.buf.push_str(&format!(
                        "    {} {};\n",
                        self.c_type_for(&p.ty),
                        mangle(&p.name.name)
                    ));
                }
            }
        }
        for member in &c.members {
            if let ClassMember::Field(f) = member {
                self.buf.push_str(&format!(
                    "    {} {};\n",
                    self.c_type_for(&f.ty),
                    mangle(&f.name.name)
                ));
            }
        }
        self.buf.push_str("};\n\n");
    }

    fn emit_class_member_decls(&mut self, c: &ClassDecl) {
        let name = &c.name.name;
        if let Some(con) = find_constructor(c) {
            let sig = self.construct_signature(name, con);
            self.buf.push_str(&format!("{sig};\n"));
        } else {
            // Always emit a no-arg constructor so calling Box() works
            // even when the class has no explicit `construct()`.
            self.buf.push_str(&format!(
                "static phc_obj_{name}* phc_construct_{name}(void);\n"
            ));
        }
        for member in &c.members {
            if let ClassMember::Method(m) = member {
                let sig = self.method_signature(name, m);
                self.buf.push_str(&format!("{sig};\n"));
            }
        }
        // Trait method mixins: emit one method per `use Trait;` from
        // the resolver's trait declarations.
        for member in &c.members {
            if let ClassMember::TraitUse(tu) = member {
                if let Some(trait_name) = tu.path.last().map(|i| i.name.as_str()) {
                    if let Some(t) = find_trait(self.file, trait_name) {
                        for m in &t.methods {
                            let sig = self.method_signature(name, m);
                            self.buf.push_str(&format!("{sig};\n"));
                        }
                    }
                }
            }
        }
    }

    fn emit_class_bodies(&mut self, c: &ClassDecl) {
        let name = c.name.name.clone();
        // Constructor body.
        if let Some(con) = find_constructor(c) {
            let sig = self.construct_signature(&name, con);
            self.buf.push_str(&sig);
            self.buf.push_str(" {\n");
            self.buf.push_str(&format!(
                "    phc_obj_{name}* phc_var_this = phc_alloc(sizeof(*phc_var_this));\n"
            ));
            // Promoted params copy into the field.
            for p in &con.params {
                if p.promoted {
                    self.buf.push_str(&format!(
                        "    phc_var_this->{name_p} = phc_var_{name_p};\n",
                        name_p = mangle(&p.name.name)
                    ));
                }
            }
            // Field defaults run before the user body.
            self.emit_field_defaults(c);
            for stmt in &con.body.statements {
                self.emit_stmt(stmt, 1);
            }
            self.buf.push_str("    return phc_var_this;\n}\n\n");
        } else {
            // Default no-arg constructor.
            self.buf.push_str(&format!(
                "static phc_obj_{name}* phc_construct_{name}(void) {{\n"
            ));
            self.buf.push_str(&format!(
                "    phc_obj_{name}* phc_var_this = phc_alloc(sizeof(*phc_var_this));\n"
            ));
            self.emit_field_defaults(c);
            self.buf.push_str("    return phc_var_this;\n}\n\n");
        }
        // Method bodies (own).
        for member in &c.members {
            if let ClassMember::Method(m) = member {
                let sig = self.method_signature(&name, m);
                self.buf.push_str(&sig);
                self.buf.push_str(" {\n");
                for stmt in &m.body.statements {
                    self.emit_stmt(stmt, 1);
                }
                self.buf.push_str("}\n\n");
            }
        }
        // Trait-mixin method bodies: emit each trait method as a
        // class-local function so the dispatch path is uniform.
        for member in &c.members {
            if let ClassMember::TraitUse(tu) = member {
                if let Some(trait_name) = tu.path.last().map(|i| i.name.as_str()) {
                    if let Some(t) = find_trait(self.file, trait_name) {
                        for m in &t.methods {
                            let sig = self.method_signature(&name, m);
                            self.buf.push_str(&sig);
                            self.buf.push_str(" {\n");
                            for stmt in &m.body.statements {
                                self.emit_stmt(stmt, 1);
                            }
                            self.buf.push_str("}\n\n");
                        }
                    }
                }
            }
        }
    }

    fn emit_field_defaults(&mut self, c: &ClassDecl) {
        for member in &c.members {
            if let ClassMember::Field(f) = member {
                if let Some(default) = &f.default {
                    let v = self.emit_expr(default);
                    self.buf.push_str(&format!(
                        "    phc_var_this->{} = {};\n",
                        mangle(&f.name.name),
                        v
                    ));
                }
            }
        }
    }

    fn emit_function_decl(&mut self, f: &FunctionDecl) {
        let sig = self.function_signature(f);
        self.buf.push_str(&format!("{sig};\n"));
    }

    fn emit_function(&mut self, f: &FunctionDecl) {
        let sig = self.function_signature(f);
        self.buf.push_str(&sig);
        self.buf.push_str(" {\n");
        for stmt in &f.body.statements {
            self.emit_stmt(stmt, 1);
        }
        self.buf.push_str("}\n\n");
    }

    fn emit_main_wrapper(&mut self, file: &SourceFile) {
        let has_main = file
            .items
            .iter()
            .any(|item| matches!(item, Item::Function(f) if f.name.name == "main"));
        if !has_main {
            self.diag(
                Span::default_for_file(),
                "no `main` function: cannot emit a C entry point",
            );
            return;
        }
        self.buf.push_str("int main(int argc, char** argv) {\n");
        self.buf.push_str("    (void)argc; (void)argv;\n");
        self.buf.push_str("    phc_main();\n");
        self.buf.push_str("    return 0;\n");
        self.buf.push_str("}\n");
    }

    fn emit_stmt(&mut self, stmt: &Stmt, indent: usize) {
        let pad = "    ".repeat(indent);
        match stmt {
            Stmt::Local(b) => {
                let init = self.emit_expr(&b.value);
                self.buf.push_str(&format!(
                    "{pad}{ty} phc_var_{name} = {init};\n",
                    ty = self.c_type_for(&b.ty),
                    name = mangle(&b.name.name),
                ));
            }
            Stmt::Reassign(r) => {
                let lhs = self.emit_expr(&r.lhs);
                let rhs = self.emit_expr(&r.value);
                self.buf.push_str(&format!("{pad}{lhs} = {rhs};\n"));
            }
            Stmt::MemberAssign(m) => {
                let lhs = self.emit_expr(&m.lhs);
                let rhs = self.emit_expr(&m.value);
                self.buf.push_str(&format!("{pad}{lhs} = {rhs};\n"));
            }
            Stmt::Expr(e) => {
                let snippet = self.emit_expr(&e.expr);
                self.buf.push_str(&format!("{pad}{snippet};\n"));
            }
            Stmt::Return(r) => {
                if let Some(value) = &r.value {
                    let snippet = self.emit_expr(value);
                    self.buf.push_str(&format!("{pad}return {snippet};\n"));
                } else {
                    self.buf.push_str(&format!("{pad}return;\n"));
                }
            }
            Stmt::If(i) => {
                let mut first = true;
                for (cond, blk) in &i.branches {
                    let cond_c = self.emit_expr(cond);
                    let kw = if first { "if" } else { "else if" };
                    self.buf.push_str(&format!("{pad}{kw} ({cond_c}) {{\n"));
                    for inner in &blk.statements {
                        self.emit_stmt(inner, indent + 1);
                    }
                    self.buf.push_str(&format!("{pad}}}"));
                    first = false;
                }
                if let Some(else_blk) = &i.else_block {
                    self.buf.push_str(" else {\n");
                    for inner in &else_blk.statements {
                        self.emit_stmt(inner, indent + 1);
                    }
                    self.buf.push_str(&format!("{pad}}}\n"));
                } else {
                    self.buf.push('\n');
                }
            }
            Stmt::While(w) => {
                let cond_c = self.emit_expr(&w.cond);
                self.buf.push_str(&format!("{pad}while ({cond_c}) {{\n"));
                for inner in &w.body.statements {
                    self.emit_stmt(inner, indent + 1);
                }
                self.buf.push_str(&format!("{pad}}}\n"));
            }
            Stmt::Break { .. } => {
                self.buf.push_str(&format!("{pad}break;\n"));
            }
            Stmt::Continue { .. } => {
                self.buf.push_str(&format!("{pad}continue;\n"));
            }
            other => {
                self.diag(
                    span_of_stmt(other),
                    "statement form not yet supported by the C emitter",
                );
                self.buf
                    .push_str(&format!("{pad}phc_panic(\"codegen TODO stmt\");\n"));
            }
        }
    }

    fn emit_expr(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::IntLit { text, .. } => {
                let cleaned: String = text.chars().filter(|c| *c != '_').collect();
                format!("(int64_t){cleaned}")
            }
            Expr::FloatLit { text, .. } => {
                let cleaned: String = text.chars().filter(|c| *c != '_').collect();
                format!("(double){cleaned}")
            }
            Expr::BoolLit { value, .. } => {
                if *value {
                    "true".into()
                } else {
                    "false".into()
                }
            }
            Expr::NullLit { .. } => "phc_null()".into(),
            Expr::StrLit { parts, .. } => self.emit_string_literal(parts),
            Expr::Var { name, .. } => format!("phc_var_{}", mangle(&name.name)),
            Expr::This { .. } => "phc_var_this".into(),
            Expr::Member {
                receiver, field, ..
            } => {
                let recv = self.emit_expr(receiver);
                format!("({recv})->{}", mangle(&field.name))
            }
            Expr::Call { callee, args, .. } => self.emit_call(callee, args),
            Expr::Paren { inner, .. } => format!("({})", self.emit_expr(inner)),
            Expr::Unary { op, operand, .. } => {
                let inner = self.emit_expr(operand);
                match op {
                    UnaryOp::Not => format!("(!({inner}))"),
                    UnaryOp::Neg => format!("(-({inner}))"),
                    UnaryOp::Await => inner, // sync passthrough
                }
            }
            Expr::Binary { op, lhs, rhs, .. } => self.emit_binary(*op, lhs, rhs),
            Expr::Cast { value, ty, .. } => {
                let inner = self.emit_expr(value);
                let target = self.c_type_for(ty);
                format!("(({target})({inner}))")
            }
            Expr::Static { ty, member, .. } => {
                if let Expr::TypeName { name, .. } = ty.as_ref() {
                    if self.is_enum(&name.name) {
                        return format!("phc_enum_{}_{}", name.name, member.name);
                    }
                }
                self.diag(
                    span_of_expr(expr),
                    "static access not yet supported in this context",
                );
                "phc_panic(\"codegen TODO static\")".into()
            }
            Expr::Match {
                scrutinee, arms, ..
            } => self.emit_match(scrutinee, arms, expr),
            other => {
                self.diag(
                    span_of_expr(other),
                    "expression form not yet supported by the C emitter",
                );
                "phc_panic(\"codegen TODO expr\")".into()
            }
        }
    }

    /// Emit a `match` expression as a GCC statement-expression
    /// `({...; result;})`. Uses `__phc_match_<lo>` for the scrutinee
    /// and `__phc_result_<lo>` for the captured result; the `<lo>`
    /// suffix keeps nested matches from colliding.
    fn emit_match(&mut self, scrutinee: &Expr, arms: &[MatchArm], whole: &Expr) -> String {
        let host_lo = span_of_expr(whole).lo;
        // Match result type: typecheck records Match as Unknown (no
        // unifier yet), so fall back to the first arm body whose
        // type is concrete.
        let result_ty = arms
            .iter()
            .find_map(|arm| {
                let t = self.typed.expr_types.get(&span_of_expr(&arm.body))?;
                if matches!(t, Ty::Unknown) {
                    None
                } else {
                    Some(self.ty_to_c(t))
                }
            })
            .unwrap_or_else(|| "int64_t".into());
        let scrut_ty = self
            .typed
            .expr_types
            .get(&span_of_expr(scrutinee))
            .map(|t| self.ty_to_c(t))
            .unwrap_or_else(|| "int64_t".into());
        let scrut_c = self.emit_expr(scrutinee);
        let scrut_var = format!("__phc_match_{host_lo}");
        let result_var = format!("__phc_result_{host_lo}");
        let mut body = String::new();
        body.push_str(&format!("{scrut_ty} {scrut_var} = {scrut_c}; "));
        body.push_str(&format!("{result_ty} {result_var}; "));
        body.push_str(&format!("bool __phc_matched_{host_lo} = false; "));
        // Independent `if`s rather than `else if` chain: a pattern
        // can match (cond=true) but its guard can fail; the next
        // arm must still get a chance. The matched flag short-
        // circuits both pieces.
        for arm in arms {
            let cond = self.pattern_condition(&arm.pattern, &scrut_var);
            let captures = pattern_captures(&arm.pattern, &scrut_ty, &scrut_var);
            let guard = arm
                .guard
                .as_ref()
                .map(|g| self.emit_expr(g))
                .unwrap_or_else(|| "true".into());
            let body_c = self.emit_expr(&arm.body);
            body.push_str(&format!(
                "if (!__phc_matched_{host_lo} && ({cond})) {{ {captures} if ({guard}) {{ {result_var} = {body_c}; __phc_matched_{host_lo} = true; }} }} "
            ));
        }
        body.push_str(&format!(
            "if (!__phc_matched_{host_lo}) {{ phc_panic(\"no match arm\"); }} "
        ));
        format!("({{ {body} {result_var}; }})")
    }

    fn pattern_condition(&mut self, pat: &Pattern, scrut: &str) -> String {
        match pat {
            Pattern::Wildcard { .. } | Pattern::Var { .. } => "true".into(),
            Pattern::Literal(lit) => {
                let lit_c = self.emit_expr(lit);
                format!("({scrut}) == ({lit_c})")
            }
            Pattern::EnumVariant { ty, variant, .. } => {
                format!("({scrut}) == phc_enum_{}_{}", ty.name, variant.name)
            }
            Pattern::Or { atoms, .. } => {
                let parts: Vec<String> = atoms
                    .iter()
                    .map(|a| self.pattern_condition(a, scrut))
                    .collect();
                format!("({})", parts.join(" || "))
            }
        }
    }

    fn emit_binary(&mut self, op: BinOp, lhs: &Expr, rhs: &Expr) -> String {
        let lhs_c = self.emit_expr(lhs);
        let rhs_c = self.emit_expr(rhs);
        let lhs_ty = self.typed.expr_types.get(&span_of_expr(lhs));
        let rhs_ty = self.typed.expr_types.get(&span_of_expr(rhs));
        let both_string = matches!(
            (lhs_ty, rhs_ty),
            (
                Some(Ty::Primitive(Primitive::String)),
                Some(Ty::Primitive(Primitive::String))
            )
        );
        let c_op = match op {
            BinOp::Add => {
                if both_string {
                    return format!("phc_concat2({lhs_c}, {rhs_c})");
                }
                "+"
            }
            BinOp::Sub => "-",
            BinOp::Mul => "*",
            BinOp::Div => "/",
            BinOp::Rem => "%",
            BinOp::Lt => "<",
            BinOp::Le => "<=",
            BinOp::Gt => ">",
            BinOp::Ge => ">=",
            BinOp::Eq => "==",
            BinOp::Neq => "!=",
            BinOp::And => "&&",
            BinOp::Or => "||",
            BinOp::NullCoalesce => {
                self.diag(span_of_expr(lhs), "`??` codegen not yet implemented");
                return "phc_panic(\"codegen TODO ??\")".into();
            }
        };
        format!("(({lhs_c}) {c_op} ({rhs_c}))")
    }

    /// Build a `phc_string` from the literal parts. A leading text
    /// piece skips the empty-string seed so the C is a touch
    /// nicer; otherwise concat through `phc_concat2`.
    fn emit_string_literal(&mut self, parts: &[StrPart]) -> String {
        if parts.is_empty() {
            return "phc_string_lit(\"\")".to_string();
        }
        let pieces: Vec<String> = parts
            .iter()
            .map(|p| match p {
                StrPart::Text(t) => format!("phc_string_lit({})", c_string_lit(t)),
                StrPart::Expr(e) => format!("phc_to_string({})", self.emit_expr(e)),
            })
            .collect();
        let mut acc = pieces[0].clone();
        for piece in pieces.iter().skip(1) {
            acc = format!("phc_concat2({acc}, {piece})");
        }
        acc
    }

    fn emit_call(&mut self, callee: &Expr, args: &[Expr]) -> String {
        // Builtin: `Logger::info(string)` → phc_print(...).
        if let Expr::Static { ty, member, .. } = callee {
            if let Expr::TypeName { name, .. } = ty.as_ref() {
                if name.name == "Logger" && member.name == "info" {
                    let pieces: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
                    if pieces.len() == 1 {
                        return format!("phc_print({})", pieces[0]);
                    }
                    self.diag(
                        span_of_expr(callee),
                        "Logger::info expects exactly one argument in the C emitter",
                    );
                    return "phc_panic(\"Logger::info arity\")".into();
                }
            }
        }
        // Method call: $obj->method(args).
        if let Expr::Member {
            receiver, field, ..
        } = callee
        {
            let recv_c = self.emit_expr(receiver);
            // Look up class name via the receiver's typed Ty.
            let class = self.class_of_expr(receiver);
            let arg_src: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
            let mut all_args = vec![recv_c];
            all_args.extend(arg_src);
            if let Some(cls) = class {
                return format!("phc_method_{cls}_{}({})", field.name, all_args.join(", "));
            }
            self.diag(
                span_of_expr(callee),
                "method dispatch needs a known class type at the receiver",
            );
            return "phc_panic(\"codegen TODO method receiver\")".into();
        }
        // User-defined free function call OR class construction.
        if let Expr::TypeName { name, .. } = callee {
            if let Some(id) = self.resolved.top_level.get(&name.name).copied() {
                let kind = self.resolved.symbol(id).kind;
                let arg_src: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
                if kind == SymbolKind::Class {
                    let args_joined = if arg_src.is_empty() {
                        "".to_string()
                    } else {
                        arg_src.join(", ")
                    };
                    return format!("phc_construct_{}({})", name.name, args_joined);
                }
                return format!("phc_{}({})", name.name, arg_src.join(", "));
            }
        }
        self.diag(
            span_of_expr(callee),
            "call form not yet supported by the C emitter",
        );
        "phc_panic(\"codegen TODO call\")".into()
    }

    /// Best-effort class lookup for a method-call receiver. Reads
    /// the typecheck pass's expr_types map for `Ty::Path { path }`
    /// where path[0] names a known class.
    fn class_of_expr(&self, expr: &Expr) -> Option<String> {
        let span = span_of_expr(expr);
        match self.typed.expr_types.get(&span)? {
            phc_typecheck::Ty::Path { path, .. } if path.len() == 1 && self.is_class(&path[0]) => {
                Some(path[0].clone())
            }
            _ => None,
        }
    }

    fn diag(&mut self, span: Span, message: &str) {
        self.diagnostics.push(Diagnostic {
            severity: Severity::Warning,
            message: message.into(),
            span,
        });
    }
}

/// Build the C declarations needed for any Var bindings inside a
/// pattern, given the scrutinee variable name and its C type.
fn pattern_captures(pat: &Pattern, scrut_ty: &str, scrut: &str) -> String {
    let mut buf = String::new();
    collect_captures(pat, scrut_ty, scrut, &mut buf);
    buf
}

fn collect_captures(pat: &Pattern, scrut_ty: &str, scrut: &str, buf: &mut String) {
    match pat {
        Pattern::Var { name, .. } => {
            buf.push_str(&format!(
                "{scrut_ty} phc_var_{} = {scrut}; ",
                mangle(&name.name)
            ));
        }
        Pattern::Or { atoms, .. } => {
            for a in atoms {
                collect_captures(a, scrut_ty, scrut, buf);
            }
        }
        _ => {}
    }
}

fn find_constructor(c: &ClassDecl) -> Option<&ConstructDecl> {
    c.members.iter().find_map(|m| match m {
        ClassMember::Construct(c) => Some(c),
        _ => None,
    })
}

fn find_trait<'a>(file: &'a SourceFile, name: &str) -> Option<&'a TraitDecl> {
    file.items.iter().find_map(|item| match item {
        Item::Trait(t) if t.name.name == name => Some(t),
        _ => None,
    })
}

fn mangle(name: &str) -> String {
    name.replace('-', "_")
}

/// Render a Rust string as a C string literal: wrap in `"..."` and
/// escape every byte that needs it.
fn c_string_lit(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\0' => out.push_str("\\0"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\x{:02x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn span_of_stmt(stmt: &Stmt) -> Span {
    match stmt {
        Stmt::Local(b) => b.span,
        Stmt::Reassign(r) => r.span,
        Stmt::MemberAssign(m) => m.span,
        Stmt::If(i) => i.span,
        Stmt::While(w) => w.span,
        Stmt::For(f) => f.span,
        Stmt::Return(r) => r.span,
        Stmt::Break { span } | Stmt::Continue { span } => *span,
        Stmt::Expr(e) => e.span,
    }
}

fn span_of_expr(expr: &Expr) -> Span {
    use Expr::*;
    match expr {
        IntLit { span, .. }
        | FloatLit { span, .. }
        | BoolLit { span, .. }
        | NullLit { span }
        | StrLit { span, .. }
        | This { span }
        | Var { span, .. }
        | TypeName { span, .. }
        | Paren { span, .. }
        | Member { span, .. }
        | Static { span, .. }
        | Call { span, .. }
        | Index { span, .. }
        | Try { span, .. }
        | Unary { span, .. }
        | Borrow { span, .. }
        | Cast { span, .. }
        | Binary { span, .. }
        | Match { span, .. }
        | Lambda { span, .. } => *span,
    }
}

trait DefaultSpan {
    fn default_for_file() -> Span;
}

impl DefaultSpan for Span {
    fn default_for_file() -> Span {
        Span::new(phc_span::FileId(0), 0, 0)
    }
}
