// SPDX-License-Identifier: MIT
//! AST → C source emitter.
//!
//! Each expression renders as a C snippet that produces a value of
//! one of the runtime types (`int64_t`, `double`, `bool`,
//! `phc_string`). Statements render as straight C statements.
//! Anything not yet supported emits a `phc_panic("codegen TODO")`
//! call so the produced binary fails loud at the matching site.
//!
//! Codegen tracks the interpreter's I1..I7 ladder. Today: I1
//! (literals + Logger::info + interpolation) plus I2 (arithmetic +
//! locals + control flow + user function calls with args + non-void
//! returns).

use phc_ast::{BinOp, Expr, FunctionDecl, Item, SourceFile, Stmt, StrPart, UnaryOp};
use phc_errors::{Diagnostic, Severity};
use phc_semantic::Resolved;
use phc_span::Span;
use phc_typecheck::{Primitive, Ty, Typed};

use crate::CodegenOutput;

/// Emit a complete C translation unit for `file`.
pub fn emit_c(file: &SourceFile, resolved: &Resolved, typed: &Typed) -> CodegenOutput {
    let mut out = CodegenOutput::default();
    let mut emitter = Emitter {
        buf: String::new(),
        diagnostics: &mut out.diagnostics,
        resolved,
        typed,
    };
    emitter.emit_prelude();
    // Forward-declare every top-level function so call order does
    // not depend on declaration order.
    for item in &file.items {
        if let Item::Function(f) = item {
            emitter.emit_function_decl(f);
        }
    }
    emitter.buf.push('\n');
    for item in &file.items {
        if let Item::Function(f) = item {
            emitter.emit_function(f);
        }
    }
    emitter.emit_main_wrapper(file);
    out.c_source = emitter.buf;
    out
}

struct Emitter<'a> {
    buf: String,
    diagnostics: &'a mut Vec<Diagnostic>,
    resolved: &'a Resolved,
    typed: &'a Typed,
}

impl<'a> Emitter<'a> {
    fn emit_prelude(&mut self) {
        self.buf
            .push_str("/* Generated by phc-codegen — do not edit. */\n");
        self.buf.push_str("#include \"phc_runtime.h\"\n\n");
    }

    fn function_signature(&self, f: &FunctionDecl) -> String {
        let return_c = c_type_for_typeref(&f.return_type);
        let params: Vec<String> = f
            .params
            .iter()
            .map(|p| {
                format!(
                    "{} phc_var_{}",
                    c_type_for_typeref(&p.ty),
                    mangle(&p.name.name)
                )
            })
            .collect();
        let param_list = if params.is_empty() {
            "void".to_string()
        } else {
            params.join(", ")
        };
        format!("static {} phc_{}({})", return_c, f.name.name, param_list)
    }

    fn emit_function_decl(&mut self, f: &FunctionDecl) {
        let sig = self.function_signature(f);
        self.buf.push_str(&format!("{sig};\n"));
    }

    fn emit_function(&mut self, f: &FunctionDecl) {
        let sig = self.function_signature(f);
        self.buf.push_str(&sig);
        self.buf.push_str(" {\n");
        for stmt in &f.body.statements {
            self.emit_stmt(stmt, 1);
        }
        self.buf.push_str("}\n\n");
    }

    fn emit_main_wrapper(&mut self, file: &SourceFile) {
        let has_main = file
            .items
            .iter()
            .any(|item| matches!(item, Item::Function(f) if f.name.name == "main"));
        if !has_main {
            self.diag(
                Span::default_for_file(),
                "no `main` function: cannot emit a C entry point",
            );
            return;
        }
        self.buf.push_str("int main(int argc, char** argv) {\n");
        self.buf.push_str("    (void)argc; (void)argv;\n");
        self.buf.push_str("    phc_main();\n");
        self.buf.push_str("    return 0;\n");
        self.buf.push_str("}\n");
    }

    fn emit_stmt(&mut self, stmt: &Stmt, indent: usize) {
        let pad = "    ".repeat(indent);
        match stmt {
            Stmt::Local(b) => {
                let init = self.emit_expr(&b.value);
                self.buf.push_str(&format!(
                    "{pad}{ty} phc_var_{name} = {init};\n",
                    ty = c_type_for_typeref(&b.ty),
                    name = mangle(&b.name.name),
                ));
            }
            Stmt::Reassign(r) => {
                let lhs = self.emit_expr(&r.lhs);
                let rhs = self.emit_expr(&r.value);
                self.buf.push_str(&format!("{pad}{lhs} = {rhs};\n"));
            }
            Stmt::Expr(e) => {
                let snippet = self.emit_expr(&e.expr);
                self.buf.push_str(&format!("{pad}{snippet};\n"));
            }
            Stmt::Return(r) => {
                if let Some(value) = &r.value {
                    let snippet = self.emit_expr(value);
                    self.buf.push_str(&format!("{pad}return {snippet};\n"));
                } else {
                    self.buf.push_str(&format!("{pad}return;\n"));
                }
            }
            Stmt::If(i) => {
                let mut first = true;
                for (cond, blk) in &i.branches {
                    let cond_c = self.emit_expr(cond);
                    let kw = if first { "if" } else { "else if" };
                    self.buf.push_str(&format!("{pad}{kw} ({cond_c}) {{\n"));
                    for inner in &blk.statements {
                        self.emit_stmt(inner, indent + 1);
                    }
                    self.buf.push_str(&format!("{pad}}}"));
                    first = false;
                }
                if let Some(else_blk) = &i.else_block {
                    self.buf.push_str(" else {\n");
                    for inner in &else_blk.statements {
                        self.emit_stmt(inner, indent + 1);
                    }
                    self.buf.push_str(&format!("{pad}}}\n"));
                } else {
                    self.buf.push('\n');
                }
            }
            Stmt::While(w) => {
                let cond_c = self.emit_expr(&w.cond);
                self.buf.push_str(&format!("{pad}while ({cond_c}) {{\n"));
                for inner in &w.body.statements {
                    self.emit_stmt(inner, indent + 1);
                }
                self.buf.push_str(&format!("{pad}}}\n"));
            }
            Stmt::Break { .. } => {
                self.buf.push_str(&format!("{pad}break;\n"));
            }
            Stmt::Continue { .. } => {
                self.buf.push_str(&format!("{pad}continue;\n"));
            }
            other => {
                self.diag(
                    span_of_stmt(other),
                    "statement form not yet supported by the C emitter",
                );
                self.buf
                    .push_str(&format!("{pad}phc_panic(\"codegen TODO stmt\");\n"));
            }
        }
    }

    fn emit_expr(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::IntLit { text, .. } => {
                let cleaned: String = text.chars().filter(|c| *c != '_').collect();
                format!("(int64_t){cleaned}")
            }
            Expr::FloatLit { text, .. } => {
                let cleaned: String = text.chars().filter(|c| *c != '_').collect();
                format!("(double){cleaned}")
            }
            Expr::BoolLit { value, .. } => {
                if *value {
                    "true".into()
                } else {
                    "false".into()
                }
            }
            Expr::NullLit { .. } => "phc_null()".into(),
            Expr::StrLit { parts, .. } => self.emit_string_literal(parts),
            Expr::Var { name, .. } => format!("phc_var_{}", mangle(&name.name)),
            Expr::Call { callee, args, .. } => self.emit_call(callee, args),
            Expr::Paren { inner, .. } => format!("({})", self.emit_expr(inner)),
            Expr::Unary { op, operand, .. } => {
                let inner = self.emit_expr(operand);
                match op {
                    UnaryOp::Not => format!("(!({inner}))"),
                    UnaryOp::Neg => format!("(-({inner}))"),
                    UnaryOp::Await => inner, // sync passthrough
                }
            }
            Expr::Binary { op, lhs, rhs, .. } => self.emit_binary(*op, lhs, rhs),
            Expr::Cast { value, ty, .. } => {
                let inner = self.emit_expr(value);
                let target = c_type_for_typeref(ty);
                format!("(({target})({inner}))")
            }
            other => {
                self.diag(
                    span_of_expr(other),
                    "expression form not yet supported by the C emitter",
                );
                "phc_panic(\"codegen TODO expr\")".into()
            }
        }
    }

    fn emit_binary(&mut self, op: BinOp, lhs: &Expr, rhs: &Expr) -> String {
        let lhs_c = self.emit_expr(lhs);
        let rhs_c = self.emit_expr(rhs);
        let lhs_ty = self.typed.expr_types.get(&span_of_expr(lhs));
        let rhs_ty = self.typed.expr_types.get(&span_of_expr(rhs));
        let both_string = matches!(
            (lhs_ty, rhs_ty),
            (
                Some(Ty::Primitive(Primitive::String)),
                Some(Ty::Primitive(Primitive::String))
            )
        );
        let c_op = match op {
            BinOp::Add => {
                if both_string {
                    return format!("phc_concat2({lhs_c}, {rhs_c})");
                }
                "+"
            }
            BinOp::Sub => "-",
            BinOp::Mul => "*",
            BinOp::Div => "/",
            BinOp::Rem => "%",
            BinOp::Lt => "<",
            BinOp::Le => "<=",
            BinOp::Gt => ">",
            BinOp::Ge => ">=",
            BinOp::Eq => "==",
            BinOp::Neq => "!=",
            BinOp::And => "&&",
            BinOp::Or => "||",
            BinOp::NullCoalesce => {
                self.diag(span_of_expr(lhs), "`??` codegen not yet implemented");
                return "phc_panic(\"codegen TODO ??\")".into();
            }
        };
        format!("(({lhs_c}) {c_op} ({rhs_c}))")
    }

    /// Build a `phc_string` from the literal parts. A leading text
    /// piece skips the empty-string seed so the C is a touch
    /// nicer; otherwise concat through `phc_concat2`.
    fn emit_string_literal(&mut self, parts: &[StrPart]) -> String {
        if parts.is_empty() {
            return "phc_string_lit(\"\")".to_string();
        }
        let pieces: Vec<String> = parts
            .iter()
            .map(|p| match p {
                StrPart::Text(t) => format!("phc_string_lit({})", c_string_lit(t)),
                StrPart::Expr(e) => format!("phc_to_string({})", self.emit_expr(e)),
            })
            .collect();
        let mut acc = pieces[0].clone();
        for piece in pieces.iter().skip(1) {
            acc = format!("phc_concat2({acc}, {piece})");
        }
        acc
    }

    fn emit_call(&mut self, callee: &Expr, args: &[Expr]) -> String {
        // Builtin: `Logger::info(string)` → phc_print(...).
        if let Expr::Static { ty, member, .. } = callee {
            if let Expr::TypeName { name, .. } = ty.as_ref() {
                if name.name == "Logger" && member.name == "info" {
                    let pieces: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
                    if pieces.len() == 1 {
                        return format!("phc_print({})", pieces[0]);
                    }
                    self.diag(
                        span_of_expr(callee),
                        "Logger::info expects exactly one argument in the C emitter",
                    );
                    return "phc_panic(\"Logger::info arity\")".into();
                }
            }
        }
        // User-defined free function call: phc_<name>(arg, ...).
        if let Expr::TypeName { name, .. } = callee {
            if self.resolved.top_level.contains_key(&name.name) {
                let arg_src: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
                return format!("phc_{}({})", name.name, arg_src.join(", "));
            }
        }
        self.diag(
            span_of_expr(callee),
            "call form not yet supported by the C emitter",
        );
        "phc_panic(\"codegen TODO call\")".into()
    }

    fn diag(&mut self, span: Span, message: &str) {
        self.diagnostics.push(Diagnostic {
            severity: Severity::Warning,
            message: message.into(),
            span,
        });
    }
}

fn c_type_for_typeref(t: &phc_ast::TypeRef) -> &'static str {
    if t.path.len() != 1 {
        return "phc_value";
    }
    match t.path[0].name.as_str() {
        "int" => "int64_t",
        "float" => "double",
        "bool" => "bool",
        "string" => "phc_string",
        "void" => "void",
        _ => "phc_value",
    }
}

fn mangle(name: &str) -> String {
    name.replace('-', "_")
}

/// Render a Rust string as a C string literal: wrap in `"..."` and
/// escape every byte that needs it.
fn c_string_lit(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\0' => out.push_str("\\0"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\x{:02x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn span_of_stmt(stmt: &Stmt) -> Span {
    match stmt {
        Stmt::Local(b) => b.span,
        Stmt::Reassign(r) => r.span,
        Stmt::MemberAssign(m) => m.span,
        Stmt::If(i) => i.span,
        Stmt::While(w) => w.span,
        Stmt::For(f) => f.span,
        Stmt::Return(r) => r.span,
        Stmt::Break { span } | Stmt::Continue { span } => *span,
        Stmt::Expr(e) => e.span,
    }
}

fn span_of_expr(expr: &Expr) -> Span {
    use Expr::*;
    match expr {
        IntLit { span, .. }
        | FloatLit { span, .. }
        | BoolLit { span, .. }
        | NullLit { span }
        | StrLit { span, .. }
        | This { span }
        | Var { span, .. }
        | TypeName { span, .. }
        | Paren { span, .. }
        | Member { span, .. }
        | Static { span, .. }
        | Call { span, .. }
        | Index { span, .. }
        | Try { span, .. }
        | Unary { span, .. }
        | Borrow { span, .. }
        | Cast { span, .. }
        | Binary { span, .. }
        | Match { span, .. }
        | Lambda { span, .. } => *span,
    }
}

trait DefaultSpan {
    fn default_for_file() -> Span;
}

impl DefaultSpan for Span {
    fn default_for_file() -> Span {
        Span::new(phc_span::FileId(0), 0, 0)
    }
}
