// SPDX-License-Identifier: MIT
//! AST → C source emitter.
//!
//! This is the simplest thing that could possibly work for
//! `examples/hello.phc`: emit a single C translation unit whose
//! `main()` calls a translated `user_main()`, route literals through
//! the runtime's `phc_string` type, and dispatch `Logger::info(x)`
//! to `phc_print`.
//!
//! Each expression is emitted as a snippet of C that produces a
//! value of one of the runtime types (`int64_t`, `double`, `bool`,
//! `phc_string`). Statements emit straight C statements. Anything
//! the emitter does not yet handle generates a `phc_panic` call so
//! the compiled binary fails loud at the matching call site.

use phc_ast::{Expr, FunctionDecl, Item, SourceFile, Stmt, StrPart};
use phc_errors::{Diagnostic, Severity};
use phc_semantic::Resolved;
use phc_span::Span;
use phc_typecheck::Typed;

use crate::CodegenOutput;

/// Emit a complete C translation unit for `file`.
pub fn emit_c(file: &SourceFile, resolved: &Resolved, _typed: &Typed) -> CodegenOutput {
    let mut out = CodegenOutput::default();
    let mut emitter = Emitter {
        buf: String::new(),
        diagnostics: &mut out.diagnostics,
        resolved,
    };
    emitter.emit_prelude();
    for item in &file.items {
        if let Item::Function(f) = item {
            emitter.emit_function(f);
        }
        // Other Item kinds (class/enum/...) deferred — the C emitter
        // tracks the interpreter's feature ladder and grows in
        // matching slices.
    }
    emitter.emit_main_wrapper(file);
    out.c_source = emitter.buf;
    out
}

struct Emitter<'a> {
    buf: String,
    diagnostics: &'a mut Vec<Diagnostic>,
    resolved: &'a Resolved,
}

impl<'a> Emitter<'a> {
    fn emit_prelude(&mut self) {
        self.buf
            .push_str("/* Generated by phc-codegen — do not edit. */\n");
        self.buf.push_str("#include \"phc_runtime.h\"\n\n");
    }

    fn emit_function(&mut self, f: &FunctionDecl) {
        // For the hello-world slice we only emit `void`-returning
        // free functions. Other return types fail loud below.
        let returns_void = is_void_return(f);
        let c_return = if returns_void { "void" } else { "int64_t" };
        self.buf
            .push_str(&format!("static {} phc_{}(void)", c_return, f.name.name));
        self.buf.push_str(" {\n");
        for stmt in &f.body.statements {
            self.emit_stmt(stmt, 1);
        }
        if returns_void {
            // C requires the function to fall through; nothing to do.
        }
        self.buf.push_str("}\n\n");
    }

    fn emit_main_wrapper(&mut self, file: &SourceFile) {
        let has_main = file
            .items
            .iter()
            .any(|item| matches!(item, Item::Function(f) if f.name.name == "main"));
        if !has_main {
            self.diag(
                Span::default_for_file(),
                "no `main` function: cannot emit a C entry point",
            );
            return;
        }
        self.buf.push_str("int main(int argc, char** argv) {\n");
        self.buf.push_str("    (void)argc; (void)argv;\n");
        self.buf.push_str("    phc_main();\n");
        self.buf.push_str("    return 0;\n");
        self.buf.push_str("}\n");
    }

    fn emit_stmt(&mut self, stmt: &Stmt, indent: usize) {
        let pad = "    ".repeat(indent);
        match stmt {
            Stmt::Local(b) => {
                let init = self.emit_expr(&b.value);
                self.buf.push_str(&format!(
                    "{pad}{ty} phc_var_{name} = {init};\n",
                    ty = c_type_for(&b.ty),
                    name = mangle(&b.name.name),
                ));
            }
            Stmt::Expr(e) => {
                let snippet = self.emit_expr(&e.expr);
                self.buf.push_str(&format!("{pad}{snippet};\n"));
            }
            Stmt::Return(r) => {
                if let Some(value) = &r.value {
                    let snippet = self.emit_expr(value);
                    self.buf.push_str(&format!("{pad}return {snippet};\n"));
                } else {
                    self.buf.push_str(&format!("{pad}return;\n"));
                }
            }
            other => {
                self.diag(
                    span_of_stmt(other),
                    "statement form not yet supported by the C emitter",
                );
                self.buf
                    .push_str(&format!("{pad}phc_panic(\"codegen TODO\");\n"));
            }
        }
    }

    fn emit_expr(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::IntLit { text, .. } => {
                let cleaned: String = text.chars().filter(|c| *c != '_').collect();
                format!("(int64_t){cleaned}")
            }
            Expr::FloatLit { text, .. } => {
                let cleaned: String = text.chars().filter(|c| *c != '_').collect();
                format!("(double){cleaned}")
            }
            Expr::BoolLit { value, .. } => {
                if *value {
                    "true".into()
                } else {
                    "false".into()
                }
            }
            Expr::NullLit { .. } => "phc_null()".into(),
            Expr::StrLit { parts, .. } => self.emit_string_literal(parts),
            Expr::Var { name, span } => {
                let _ = span;
                format!("phc_var_{}", mangle(&name.name))
            }
            Expr::Call { callee, args, .. } => self.emit_call(callee, args),
            Expr::Paren { inner, .. } => format!("({})", self.emit_expr(inner)),
            other => {
                self.diag(
                    span_of_expr(other),
                    "expression form not yet supported by the C emitter",
                );
                "phc_panic(\"codegen TODO\")".into()
            }
        }
    }

    /// Build a `phc_string` from the literal parts, concatenating
    /// every interpolation as we go via `phc_concat2`.
    fn emit_string_literal(&mut self, parts: &[StrPart]) -> String {
        let mut acc = "phc_string_lit(\"\")".to_string();
        for part in parts {
            let piece = match part {
                StrPart::Text(t) => format!("phc_string_lit({})", c_string_lit(t)),
                StrPart::Expr(e) => format!("phc_to_string({})", self.emit_expr(e)),
            };
            acc = format!("phc_concat2({acc}, {piece})");
        }
        acc
    }

    fn emit_call(&mut self, callee: &Expr, args: &[Expr]) -> String {
        // Builtin: `Logger::info(string)` → phc_print(...).
        if let Expr::Static { ty, member, .. } = callee {
            if let Expr::TypeName { name, .. } = ty.as_ref() {
                if name.name == "Logger" && member.name == "info" {
                    let pieces: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
                    if pieces.len() == 1 {
                        return format!("phc_print({})", pieces[0]);
                    }
                    self.diag(
                        span_of_expr(callee),
                        "Logger::info expects exactly one argument in the C emitter",
                    );
                    return "phc_panic(\"Logger::info arity\")".into();
                }
            }
        }
        // User-defined free function call: phc_<name>(...).
        if let Expr::TypeName { name, .. } = callee {
            if let Some(_id) = self.resolved.top_level.get(&name.name).copied() {
                let arg_src: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
                return format!("phc_{}({})", name.name, arg_src.join(", "));
            }
        }
        self.diag(
            span_of_expr(callee),
            "call form not yet supported by the C emitter",
        );
        "phc_panic(\"codegen TODO call\")".into()
    }

    fn diag(&mut self, span: Span, message: &str) {
        self.diagnostics.push(Diagnostic {
            severity: Severity::Warning,
            message: message.into(),
            span,
        });
    }
}

fn is_void_return(f: &FunctionDecl) -> bool {
    f.return_type.path.len() == 1 && f.return_type.path[0].name == "void"
}

fn c_type_for(t: &phc_ast::TypeRef) -> &'static str {
    match t.path.last().map(|i| i.name.as_str()).unwrap_or("") {
        "int" => "int64_t",
        "float" => "double",
        "bool" => "bool",
        "string" => "phc_string",
        "void" => "void",
        _ => "phc_value", // catch-all opaque box; defined in runtime
    }
}

fn mangle(name: &str) -> String {
    name.replace('-', "_")
}

/// Render a Rust string as a C string literal: wrap in `"..."` and
/// escape every byte that needs it.
fn c_string_lit(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\0' => out.push_str("\\0"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\x{:02x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn span_of_stmt(stmt: &Stmt) -> Span {
    match stmt {
        Stmt::Local(b) => b.span,
        Stmt::Reassign(r) => r.span,
        Stmt::MemberAssign(m) => m.span,
        Stmt::If(i) => i.span,
        Stmt::While(w) => w.span,
        Stmt::For(f) => f.span,
        Stmt::Return(r) => r.span,
        Stmt::Break { span } | Stmt::Continue { span } => *span,
        Stmt::Expr(e) => e.span,
    }
}

fn span_of_expr(expr: &Expr) -> Span {
    use Expr::*;
    match expr {
        IntLit { span, .. }
        | FloatLit { span, .. }
        | BoolLit { span, .. }
        | NullLit { span }
        | StrLit { span, .. }
        | This { span }
        | Var { span, .. }
        | TypeName { span, .. }
        | Paren { span, .. }
        | Member { span, .. }
        | Static { span, .. }
        | Call { span, .. }
        | Index { span, .. }
        | Try { span, .. }
        | Unary { span, .. }
        | Borrow { span, .. }
        | Cast { span, .. }
        | Binary { span, .. }
        | Match { span, .. }
        | Lambda { span, .. } => *span,
    }
}

trait DefaultSpan {
    fn default_for_file() -> Span;
}

impl DefaultSpan for Span {
    fn default_for_file() -> Span {
        Span::new(phc_span::FileId(0), 0, 0)
    }
}
