[package]
name = "phc"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "The PHC compiler and CLI"

[[bin]]
name = "phc"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
phc-interp = { path = "../crates/phc-interp" }
phc-parser = { path = "../crates/phc-parser" }
phc-semantic = { path = "../crates/phc-semantic" }
phc-typecheck = { path = "../crates/phc-typecheck" }
phc-borrowcheck = { path = "../crates/phc-borrowcheck" }
phc-lsp = { path = "../crates/phc-lsp" }
tokio = { workspace = true }
phc-span = { path = "../crates/phc-span" }
phc-build = { path = "../crates/phc-build" }
phc-pkg = { path = "../crates/phc-pkg" }
phc-ast = { path = "../crates/phc-ast" }
phc-errors = { path = "../crates/phc-errors" }
